import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import VerificationBanner from "./components/VerificationBanner";
import PasswordGate from "./components/PasswordGate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-sans antialiased"
        style={{ backgroundColor: '#0E1116', color: '#E5E7EB' }}
      >
        <PasswordGate>
          <AuthProvider>
            <VerificationBanner />
            {children}
          </AuthProvider>
        </PasswordGate>
      </body>
    </html>
  );
}
