import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Fira_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import VerificationBanner from "./components/VerificationBanner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const firaMono = Fira_Mono({
  weight: "400",
  variable: "--font-fira-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${firaMono.variable} font-sans antialiased`}
        style={{ backgroundColor: '#0E1116', color: '#E5E7EB' }}
      >
        <AuthProvider>
          <VerificationBanner />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
